apiVersion: apps/v1
kind: Deployment
metadata:
  name: webpage
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: bramba/mywebpage
        ports:
        - containerPort: 80